### ISSUE TITLE
NPM@master not found

### ISSUE THREAD

**Issue by markelayan** [serverless/github-action#14]
Current runner version: '2.161.0'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v1'
Download action repository 'jakejarvis/s3-sync-action@v0.5.0'
Download action repository 'actions/npm@master'
##[warning]Failed to download action 'https://api.github.com/repos/actions/npm/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 18.464 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/actions/npm/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 17.413 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).

**Comment by tdi** [comment]
it is related to #10

**Comment by DarinDev1000** [comment]
https://github.com/serverless/github-action/issues/18#issuecomment-577419316

This pull request https://github.com/serverless/github-action/pull/19 fixes the issue.

The updated code should be:
```
on:
  push:
    branches:
      - master
name: Serverless deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS creds directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
