### ISSUE TITLE
Support for multiple serverless.yml files

### ISSUE THREAD

**Issue by morficus** [serverless/github-action#20]
I have a monorepo which holds three different Serverless projects. When deploying manually I can simply `cd` in to each directory and run `sls deploy`.

When using the GitHub workflow, is there a way to specify which directory to use as the "base" directory?

**Comment by lfreneda** [comment]
@morficus same scenario here :)

**Comment by lfreneda** [comment]
@morficus any workaround?

**Comment by bobbysoar** [comment]
@morficus @lfreneda I have a similar issue, unfortunately for the time being i had to resort to using npx serverless deploy with github's working-directory property

`      - name: Deploy Foo Stack For Dev
           run: npx serverless deploy
           working-directory: ./packages/foo`

**Comment by reganjohnson** [comment]
Here is my solution to deploy different serverless.yml based on which branch I am running the action on:

```
      - name: Setup serverless prod
        if: github.ref == 'refs/heads/master'
        run: mv serverless.prod.yml serverless.yml

      - name: Setup serverless dev
        if: github.ref == 'refs/heads/dev'
        run: mv serverless.dev.yml serverless.yml

      - name: Deploy dev
        if: github.ref == 'refs/heads/dev'
        uses: serverless/github-action@master
        with:
          args: deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy prod
        if: github.ref == 'refs/heads/master'
        uses: serverless/github-action@master
        with:
          args: deploy --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

Hope this helps someone!

**Comment by ZubkoWhatislove** [comment]
waiting for a solution to the problem ☹️

**Comment by leevi978** [comment]
Any updates on this?

**Comment by marayshi** [comment]
You can execure deploy multiple times in same file, each time with different serverless config file

Dev
```
   - name: serverless deploy dev
      uses: serverless/github-action@master
      with:
        args: deploy --config serverless_dev.yml
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

Prod
```
    - name: serverless deploy prod
      uses: serverless/github-action@master
      with:
        args: deploy --config serverless_prod.yml
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
```
