### ISSUE TITLE
Document capture of `Outputs` and `sls info` results

### ISSUE THREAD

**Issue by matthewpoer** [serverless/github-action#26]
This took a while to figure out so I'd like to share and advise that it'd be nice to see in the README or elsewhere in the documentation.

My use case was that I needed to capture some of my `resources.Outputs` from a serverless deployment for use with later scripting. For example, here's an excerpt from my `serverless.yml` file:

```
resources:
  Resources:
    host:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-0f2b4fc905b0bd1f1
        InstanceType: t2.medium
  Outputs:
    PublicDnsName:
      Description: "host public URL"
      Value: !GetAtt host.PublicDnsName
```

With that in place I can run `sls info --verbose` and capture in that output is the desired `PublicDnsName` _but_ I have to grep and adjust for that, e.g.

```
sls info --verbose | grep PublicDnsName | cut -c 16-
```

All that said, I found it difficult to perform that scrub-and-grab sequence in a Github Action using this container, but finally landed on overwriting the `entrypoint` and prefixing my command with a `-c`, which is appended as an argument to the bash invocation. It's a bit confusing to me still, but it's functional:

```
name: Deploy to Amazon EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run serverless deployment
      uses: serverless/github-action@v1.53.0
      with:
        args: deploy --stage=dev --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        SLS_DEBUG: 1
    - name: Export sls/aws-ec2 host
      uses: serverless/github-action@v1.53.0
      with:
        args: -c "serverless info --stage=dev --verbose | grep PublicDnsName | cut -c 16- > host.txt"
        entrypoint: /bin/bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        SLS_DEBUG: 1
    - name: Show site URL for review and testing
      run: |
        export host=$(cat host.txt)
        echo http://$host/
```

**Comment by DavidWells** [comment]
Solid tip 

I made a plugin that outputs outputs into a "manifest file" https://www.npmjs.com/package/serverless-manifest-plugin

This might help avoid some hardcode greps.

I'd love if `sls deploy` had a `--json` flag to output a simple structure to parse with `jq`

**Comment by matthewpoer** [comment]
@DavidWells thanks, and nice plugin. I think we've identified the same need. The first time I saw you could set output params. this way in sls I thought it was great. When I found the only way to access them was re-running sls, requiring re-authorization and again setting the stage _and_ the verbose flag, then having to dig for the result, I was not pleased.

**Comment by marcelloromani** [comment]
Thank you @matthewpoer 

Just want to add that I'm using `v2.18.0` and had to change the shell to `/bin/sh`.

**Comment by miltonhit** [comment]
Hello everyone.
I didn't quite understand. How do you want to do this.


I triend this
```
serverless.yml:

functions:
  app:
    handler: com.br.hub.facecomparison.config.StreamLambdaHandler
    name: ${self:service}-${self:custom.stage}
    events:
    - http:
        cors: true
        path: '/facecomparison/{proxy+}'
        method: any


workflow:
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy --stage prd
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

But I need an API Gateway URL generated in this step, to put in my FRONTEND app.
Example:

```
- name: get URL
- run: echo $API_GATEWAY_URL
```

In my local environment, I can do this, with this plugin:
serverless-manifest-plugin

```
API_GATEWAY_URL=$(serverless manifest --json --aws-profile hubia-deploy --stage prd | jq -r '.prd.urls.apiGateway')
```

Can you help me? :(
