### ISSUE TITLE
Add examples for using Serverless Plugins

### ISSUE THREAD

**Issue by matthewpoer** [serverless/github-action#28]
Sharing an example of using this Action with one or more SLS Serverless plugins. Would be nice to add some notes around this to the `README.md`. The key is to set both `args` and `entrypoint` on the step.

Similar tactic is used in #26 to capture `resources.Outputs` data. 

```
name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stages:
          - stage: 'dev'
            AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY_DEV'
            AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID_DEV'
          - stage: 'prod'
            AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY_PROD'
            AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID_PROD'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install VPC Plugin and Deploy
      uses: serverless/github-action@v1.53.0
      with:
        args: -c "serverless plugin install --name serverless-vpc-discovery && serverless deploy --stage=${{ matrix.stages.stage }} --verbose"
        entrypoint: /bin/bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets[matrix.stages.AWS_ACCESS_KEY_ID] }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets[matrix.stages.AWS_SECRET_ACCESS_KEY] }}
        SLS_DEBUG: 1
```

**Comment by benjefferies** [comment]
I was just about to start figuring this out but you've saved me some time. Thanks for the issue/documentation @matthewpoer

**Comment by matthewpoer** [comment]
Update for all those who find this the hard way: `serverless plugin install ...` will find and install the latest version of a plugin. You can tag specific versions

**Comment by matthewpoer** [comment]
Update for all those who find this the hard way: `serverless plugin install ...` will find and install the latest version of a plugin. You can tag specific versions, but I found this easier:

```yaml
    - name: Install SLS Plugins and Deploy
      uses: serverless/github-action@v1.53.0
      with:
        args: -c "npm install --also=dev && npm list -g && npm list && serverless deploy --stage=${{ matrix.stages.stage }} --verbose"
        entrypoint: /bin/bash
```

The extra `npm list` bits are nice to check versions :D
