### ISSUE TITLE
Failed to download action.

### ISSUE THREAD

**Issue by webhacking** [serverless/github-action#29]
Failed to download action 'https://api.github.com/repos/actions/npm/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).

**Comment by webhacking** [comment]
Here my configuration

```
on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm ci
      uses: actions/npm@master
      with:
        args: install
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_EMOTION_IAM_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_EMOTION_IAM_SECRET_KEY }}

```

**Comment by kaykhancheckpoint** [comment]
Have the same issue, did you manage to fix this?

**Comment by fabianriewe** [comment]
Hi, i fixed the issue by using a new step:

```
on:
  release:
    types: [prereleased, released]

name: Deploy serverless function
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
