### ISSUE TITLE
"python3.7 not found! Try the pythonBin option."

### ISSUE THREAD

**Issue by ScottBrenner** [serverless/github-action#3]
Using Python 3.7 in my `serverless.yml`:
```
provider:
  runtime: python3.7
```

When I create a pipeline using this action it fails with
```
Error --------------------------------------------------
 
  python3.7 not found! Try the pythonBin option.
```

What Python version(s) are supported, could we add 3.7?

**Comment by ScottBrenner** [comment]
Actually it looks like the only supported runtime for the image is Node.js, right?

**Comment by khamaileon** [comment]
@ScottBrenner Do you have Python 3.7 installed locally ?

**Comment by ScottBrenner** [comment]
@khamaileon Yes -
```
$ python3 --version
Python 3.7.2
```

**Comment by Vlaaaaaaad** [comment]
Did anybody manage to get this working?

**Comment by Vlaaaaaaad** [comment]
I can confirm that changing the base image works. I did the change in [a fork](https://github.com/Vlaaaaaaad/github-action/blob/python-too/Dockerfile) using the first Dockerhub image I found with both Python 3.7 and Node:
```diff
- FROM node:10-slim
+ FROM nikolaik/python-nodejs:python3.7-nodejs10
```

and successfully used the resulting action:
```
- name: Deploy
        uses: vlaaaaaaad/github-action@python-too
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
          SLS_DEBUG: "*"
        with:
          args: deploy
```

I firmly believe that the official Serverless action should have support for **all** runtimes baked in by default.

**Comment by khakiout** [comment]
Can I know how you are doing this. I managed to deploy a test serverless application (Java) using this action

```
name: CI

on: [push]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Serverless deployment
      uses: serverless/github-action@v1.49.0
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLS_DEBUG: "*"
```

**Comment by Vlaaaaaaad** [comment]
@khakiout what do you want to know? I basically just do a `npm install` to get all the Serverless plugins installed and then I call the action which does the dependency install, packaging, and deploy. 

The job file:
```yaml
Deploy:
  runs-on: ubuntu-latest
  needs: Test

  steps:
    - name: Clone repo
      uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Setup Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12.x

    - name: Install dependencies
      run: |
        npm install

    - name: Deploy
      uses: vlaaaaaaad/github-action@python-too
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # SLS_DEBUG: "*"
      with:
        args: deploy
```

**Comment by dschep** [comment]
The best solution to this will be to rewrite as a javascript action rather than a Docker action and then you can use `actions/setup-python` before the serverless action to ensure you have Python. I've been using my own fork of this for my python projects: https://github.com/dschep/serverless-python-action

**Comment by ScottBrenner** [comment]
Seems https://github.com/marketplace/actions/serverless-with-python-requirements supports it

**Comment by jackdcasey** [comment]
A bit late to the party, In case anyone is having the same issue with Python 3.8, this worked for me: 

```
 - name: Serverless
      uses: jackdcasey/github-action@python3.8-nodejs13
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

```

Following what @Vlaaaaaaad did before, I've [forked](https://github.com/jackdcasey/github-action/tree/python3.8-nodejs13) the action, and updated the docker image to one with Python 3.8 installed. 

Hope this can save some headaches! 😁
