### ISSUE TITLE
Cannot deploy 

### ISSUE THREAD

**Issue by arpecop** [serverless/github-action#33]
```
name: Deploy
on:
    push:
        branches:
            - master
jobs:
    deploy:
        name: Deployment
        runs-on: ubuntu-latest
        strategy:
            matrix:
                stages:
                    - stage: 'prod'
                      AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY_PROD'
                      AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID_PROD'
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: npm install and build
              run: npm install
            - name: Install VPC Plugin and Deploy
              uses: serverless/github-action@v1.53.0
              with:
                  args: -c "serverless deploy --stage=${{ matrix.stages.stage }} --verbose"
                  entrypoint: /bin/bash
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
![Screenshot 2020-06-26 at 17 21 19](https://user-images.githubusercontent.com/168974/85867608-d18dcb00-b7d1-11ea-9cbd-291c81226df6.png)

I added GitHub to serverless and my repos are listing there
