### ISSUE TITLE
Error: SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by ffxsam** [serverless/github-action#35]
I'm getting the following error when trying to use this action:

> ERROR in Sentry CLI Plugin: Command failed: /github/workspace/node_modules/@sentry/cli/sentry-cli releases new 411cf6121b7831da3a5b8ed631812772f0e02d62
error: API request failed
  caused by: [60] SSL peer certificate or SSH remote key was not OK

The step config:

```yaml
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
