### ISSUE TITLE
DOTENV cannot find .env file

### ISSUE THREAD

**Issue by teamzz111** [serverless/github-action#36]
Hi guys, assuming

**Comment by DavideViolante** [comment]
Secrets are stored in repo Settings -> Secrets, so a secret with `SERVERLESS_ACCESS_KEY` must be created in the repo to use this action.

**Comment by teamzz111** [comment]
I've setted secrets, but error persists.

![image](https://user-images.githubusercontent.com/37392536/92298964-ed20fa80-ef13-11ea-920c-f71d5d9d3ae1.png)

**Comment by mlg87** [comment]
@teamzz111 are you using `serverless-dotenv-plugin`?

**Comment by teamzz111** [comment]
Yes

**Comment by mlg87** [comment]
@teamzz111 remove that from your plugins and it will work. that plugin is attempting to find an `.env` file (which i assume you havent checked in)

**Comment by zuojianghua** [comment]
i use .env for TENCENT_SECRET_ID & TENCENT_SECRET_KEY, but it still need `serverless login`

how do I distinguish between AWS and TENCENT Cloud?

**Comment by teamzz111** [comment]
I use .env vars for databases, keys etc. I really need this file

**Comment by prateek105** [comment]
@teamzz111 hi, I am facing same issue in github actions. Did you find a solution for this issue?

**Comment by teamzz111** [comment]
Remove the plugin or remove your env from gitignore.

**Comment by prateek105** [comment]
I have removed the plugin. Still when I deploy lambda via github actions I can not see any environment variables on aws console. How do i setup the environment variables for the lambda function. I am using [this](https://github.com/marketplace/actions/serverless) for my gihub actions

**Comment by uvinod** [comment]
I'm facing the same issue.

**Comment by sehrish30** [comment]
Solution is this https://github.com/marketplace/actions/setup-serverless-environment

Add this to your GitHub actions file to add environment variables
then you can use ${env:FACEBOOK_CLIENT_ID} in your serverless.yml file when deploying with serverless

env:
  FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
  FACEBOOK_SECRET_KEY: ${{ secrets.FACEBOOK_SECRET_KEY }}

**Comment by danielnmai** [comment]
> Solution is this https://github.com/marketplace/actions/setup-serverless-environment
> 
> Add this to your GitHub actions file to add environment variables then you can use ${env:FACEBOOK_CLIENT_ID} in your serverless.yml file when deploying with serverless
> 
> env: FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }} FACEBOOK_SECRET_KEY: ${{ secrets.FACEBOOK_SECRET_KEY }}

Link does not work? I'm facing the same problem, even after removing the plugin, it still fails to load the env vars. My deploy script:

```
name: Deploy NodeJS API to AWS Lambda with Serverless Framework

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build code
        run: yarn install

      - name: Transpile JS code
        run: yarn build

      - name: Deploy to AWS
        uses: serverless/github-action@v3.2.0
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USER: ${{ vars.DB_USER }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
