### ISSUE TITLE
Deploy failing: This command can only be run in a Serverless service directory.

### ISSUE THREAD

**Issue by Blackglade** [serverless/github-action#53]
I have a mono repo project and a separate directory that contains the serverless yaml file. Is there a way to set the directory to execute from in the github action. 

I tried doing something like this:

```
    - name: Navigate to serverless
      run: cd serverless

    - name: Serverless Deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

but without any luck.

**Comment by the1adi** [comment]
I am experiencing the same issue. I tried using the working directory setting and it still did not work.

This is my main.yml:
`name: Deploy master branch

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - name: serverless deploy
              uses: serverless/github-action@master
              with:
                  args: deploy
              env:
                  # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
                  # or if using AWS credentials directly
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
`

This gave me the same error.

**Comment by deathemperor** [comment]
couldn't find anyway to make it run either. I think it's because of this:

`-v "/home/runner/work/berry/berry":"/github/workspace"`

By default the serverless docker maps the parent folder. Would be nice if there's an option to change that.

**Comment by deathemperor** [comment]
Ended up writing my own commands.

```yml
name: GitHub Actions Deploy ID Dev
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn workspace @berry/shared build
      - run: node ./node_modules/serverless/bin/serverless.js config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile papaya --overwrite
      - run: node ../../node_modules/serverless/bin/serverless.js deploy --aws-s3-accelerate --stage dev --verbose
        working-directory: ./services/id
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS_DEBUG: 1
```

**Comment by russellc92** [comment]
You need to set the config variable on the serverless deploy command to the path of the serverless.yml file:


```
name: serverless deploy
uses: serverless/github-action@master
with:
  args: deploy -s stage -c path/to/file/serverless.yml
```

**Comment by peimanja** [comment]
> You need to set the config variable on the serverless deploy command to the path of the serverless.yml file:
> 
> ```
> name: serverless deploy
> uses: serverless/github-action@master
> with:
>   args: deploy -s stage -c path/to/file/serverless.yml
> ```

This does not work if you are loading other files in your `serverless.yml` .
```
 Serverless Warning --------------------------------------
 
  A valid file to satisfy the declaration 'file(dev-config.yaml):environment' could not be found.
```

**Comment by StephenGrable1** [comment]
Anyone encountering this thread who's following best practices and splitting their serverless app into separate directories, follow @deathemperor solution above (or my slightly simplified one below) to roll your own deployment step for each of your services. 

Any semi-mature application will eventually need to split their code. I recommend you do not consolidate your separate services into the root folder just so this github action will work -- you will end up having to backtrack once your app grows. 

It would be great if we could add support for this eventually, but in the meantime, I'm dropping this github action and using this manual deployment setup: 

```yml
name: GitHub Actions Deploy Prod
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: node ./node_modules/serverless/bin/serverless.js config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: node ../../node_modules/serverless/bin/serverless.js deploy --stage prod --verbose
        working-directory: ./serverless/backend-api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS_DEBUG: 1

```

thanks again for the suggestion @deathemperor

**Comment by hutch120** [comment]
VERY frustrating ... feels like serverless.com is no longer really making it easier to deploy, and now is more focused on locking in customers.

It appears that the serverless client now enforces the need for `SERVERLESS_ACCESS_KEY` and given that, pretty much might as well use linked AWS account in serverless.com UX console.

My subdirectory is called `server`. Also note the use of `working-directory` at top level.

```
name: Deploy main branch serverless

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deployserver
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: node ./node_modules/serverless/bin/serverless.js deploy --stage prod --verbose
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          SLS_DEBUG: 1
```

**Comment by pgrzesik** [comment]
@hutch120 Could you elaborate more what is the problem here? Serverless never requires the use of SERVERLESS_ACCESS_KEY, what makes you think that is the case?

**Comment by hutch120** [comment]
@pgrzesik Thanks for the note. Sure... here are logs of attempting to run without `SERVERLESS_ACCESS_KEY`.  Literally the only change required to get my deploy to work is to add a valid `SERVERLESS_ACCESS_KEY` to the `env` section of the yaml file.

```
Run node ./node_modules/serverless/bin/serverless.js config credentials --provider aws --key *** --secret ***
  node ./node_modules/serverless/bin/serverless.js config credentials --provider aws --key *** --secret ***
  shell: /usr/bin/bash -e {0}
Serverless: Setting up AWS...
2s
Run node ./node_modules/serverless/bin/serverless.js deploy --stage prod --verbose
  node ./node_modules/serverless/bin/serverless.js deploy --stage prod --verbose
  shell: /usr/bin/bash -e {0}
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
 
 Serverless Error ----------------------------------------
 
  You are not currently logged in. Follow instructions in http://slss.io/run-in-cicd to setup env vars for authentication.
```

**Comment by pgrzesik** [comment]
Hey @hutch120 - thanks for responding. Based on the error message it seems like you're using Serverless Dashboard integration in your service - do you have `org` and `app` properties defined in your `serverless.yml`? If that's the case, then yes, SERVERLESS_ACCESS_KEY is required, because otherwise it would be impossible to use the Dashboard integration. If you are not using Dashboard, you can remove the `org` and `app` setttings and key will be no longer needed.

**Comment by hutch120** [comment]
@pgrzesik Thanks for the info. I stand corrected. I've updated my initial comment. FYI I guess the reason I got to the point was by following along with [this general guide](https://www.serverless.com/framework/docs/guides/dashboard) and [this CI guide](https://www.serverless.com/framework/docs/guides/cicd/running-in-your-own-cicd)

**Comment by pgrzesik** [comment]
Hey @hutch120 - happy I could help clear up some misunderstanding :+1: As for these guides, I'm looking at them and I see that the second one about CI setup might definitely be misleading, as it suggests that if you're using CI, then you need to use Dashboard which is definitely not the case. I'll bring it up internally so we can clear that confusion in documentation as well :+1:

**Comment by Schachte** [comment]
https://ryan-schachte.com/posts/serverless-deployments-with-github-actions-on-aws

I wrote a post setting this deployment up on Github actions. Might help some people out there.

**Comment by nikhuber** [comment]
I handled this issue by overriding the `ENTRYPOINT` and changing to the directory that contains my `serverless.yml` this way

```
jobs:
  deploy:
    name: deployserver
...
    steps:
      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: -c "cd ./<your-dir> && serverless deploy"
          entrypoint: /bin/sh
```

Change `<your-dir>` to your target directory.
