### ISSUE TITLE
Deploying from a subdirectory

### ISSUE THREAD

**Issue by bernier** [serverless/github-action#65]
Hi,

I would like to have the following project structure but I couldn't make it work with the v2, wondering if it's now supported.

```
.github
... workflows
backend
... serverless.yml
... all other backend files
frontend
... frontend files
```

Basically, it doesn't seem possible to define a working directory for the serverless app.
This is what I'm using for the frontend directory in my pipeline.yaml, I would like to do something similar for the backend directory.

```
    - name: Building Frontend
      run: npm run build
      working-directory: ${{ env.working-directory-frontend }}

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: "frontend/dist" 
```

Thanks!

**Comment by DavideViolante** [comment]
Try this:
```yaml
  args: -c "cd ./<your-dir> && serverless deploy"
  entrypoint: /bin/sh
```
from https://github.com/serverless/github-action/issues/53#issuecomment-1059839383

**Comment by aacitelli** [comment]
^ The above workaround worked fine for me, this can likely be closed

**Comment by sgd2z** [comment]
For anyone looking for a solution. You don't even need this github action:

```
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./path/subfolder
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g serverless
      - run: serverless deploy
```
