### ISSUE TITLE
Use aws credentials from aws-actions/configure-aws-credentials@v1

### ISSUE THREAD

**Issue by nnuguid-locii** [serverless/github-action#66]
i need to assume a role in order to deploy. aws-actions has a way to this. is there a way for the serverless/githhub-action to use those credentials?

**Comment by dan-newscorp** [comment]
+1

**Comment by gm-mmurillo** [comment]
+1

**Comment by dfelsman-ta** [comment]
+1

**Comment by nitrocode** [comment]
Has anyone able to get this work using the latest https://github.com/aws-actions/configure-aws-credentials ?

I imagine it's the same setup as @Pudding124 mentioned above https://github.com/serverless/github-action/issues/66#issuecomment-1316746468

**Comment by ryanlawson** [comment]
The `configure-aws-credentials` action has the following [outputs](https://github.com/aws-actions/configure-aws-credentials/blob/main/action.yml):

- `aws-access-key-id`
- `aws-secret-access-key`
- `aws-session-token`

You can pass them into the Serverless action as environment variables.

For example:

```yaml
- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v1
  id: credentials # note `id` needs to be set
  with:
     role-session-name: assume_role
     role-to-assume: ${{ secrets.IAM_ROLE }}
     aws-region: us-east-1

- name: serverless deploy
  uses: serverless/github-action@v3.2
  with:
    args: deploy --use-local-credentials
  env:
    AWS_ACCESS_KEY_ID: ${{ steps.credentials.outputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ steps.credentials.outputs.aws-secret-access-key }}
```
