### ISSUE TITLE
No such file or directory 'package.json'

### ISSUE THREAD

**Issue by willgorick** [serverless/github-action#69]
I have the following steps in my github action .yml file:
`steps:
      - uses: actions/checkout@v2
      - name: Enter serverless dir and deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./src/serverless && serverless plugin install --name serverless-plugin-tracing && serverless deploy"
          entrypoint: /bin/sh`
          
But I'm getting an error, despite the fact that I do have a package.json file in my src/serverless folder:
` npm ERR! enoent ENOENT: no such file or directory, open '/github/home/.npm/_cacache/tmp/jrJNSF/package.json'`

Does anyone know of a workaround/solution for this?

**Comment by pmckl** [comment]
The indent is wrong in you example, the entrypoint should be in the same level as args:

```yaml
      - uses: actions/checkout@v2
      - name: Enter serverless dir and deploy
         uses: serverless/github-action@v3.1
         with:
           args: -c "cd ./src/serverless && serverless plugin install --name serverless-plugin-tracing && serverless deploy"
           entrypoint: /bin/sh
```
