### ISSUE TITLE
No support for lambda with docker images

### ISSUE THREAD

**Issue by jmrodriguez-lab** [serverless/github-action#72]
Deploying lambdas using docker images instead of layers is possible with serverless as explained [here](https://www.serverless.com/blog/container-support-for-lambda). An example:

```yaml
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-1
  ecr:
    images:
        python_lambda:
        path: ./
...
```

however, this requires `docker` command to be available in docker image specified in the `Dockerfile`, which is not installed.

Could it be added, please? :-)

**Comment by gshigenaka01** [comment]
I had this same issue as well but ended up not using this github-action. Try installing serverless manually and running the deploy command and that worked for me.

**Comment by arshamg** [comment]
Did you find any solution to this using Github Actions?
I'm also considering using the CI/CD service from Serverless - any experience there?

**Comment by gshigenaka01** [comment]
This worked for me:
```yml
on:
  push:
    branches: [ "staging", "main" ]
jobs:     
  <job_name_here>:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: install-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: install serverless
      run: npm i -g serverless
    - name: severless deploy
      run: sls deploy --verbose --force
```
