### ISSUE TITLE
`pipenv lock --keep-outdated` Exited with code 1

### ISSUE THREAD

**Issue by kryptiksage** [serverless/github-action#76]
Action failed with the error `pipenv lock --keep-outdated Exited with code 1`

```yaml
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.4.0"
      
      - name: Serverless deploy
        uses: serverless/github-action@v3
        env:
          AWS_ACCESS_KEY_ID: xxx
          AWS_SECRET_ACCESS_KEY: xxx
        with:
          args: -c "serverless create_domain  && serverless deploy"
          entrypoint: /bin/sh
```
