### ISSUE TITLE
BUG: Attempted to run an interactive setup in non TTY environment.

### ISSUE THREAD

**Issue by jochman** [serverless/github-action#77]
I'm using a very simple workflow:
```yaml
name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serverless/github-action@v3.1.0
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
```

and I'm getting:

```sh
Error:
Attempted to run an interactive setup in non TTY environment.
If that's intended, run with the SLS_INTERACTIVE_SETUP_ENABLE=1 environment variable
```

**Comment by Emyboy** [comment]
I'm getting same error when tying to create a new project

![image](https://user-images.githubusercontent.com/34845973/236282411-5ddadd41-a0c9-4d3d-8e0f-ef94850e343e.png)

**Comment by ryanlawson** [comment]
You need to supply arguments with `args`. The action just runs `serverless` so it's expecting user input.

```yaml
name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: serverless/github-action@v3.1.0
        args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
```
