### ISSUE TITLE
Undefined env vars for nodejs code

### ISSUE THREAD

**Issue by RaFaTEOLI** [serverless/github-action#85]
When I deploy my nodejs api through the action it doesn't populate the nodejs env var for my database url, and it stays as undefined.

However it works for the aws keys.

**BTW**: it works normally when I deploy from my CLI, issue is only with the action.

How the deploy step looks like:

```yml
- name: serverless deploy --stage=dev
      uses: serverless/github-action@v3.2
      with:
        args: deploy
      env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           DATABASE_URL: ${{ secrets.DATABASE_URL }}
```
