### ISSUE TITLE
deploy command with input parameters

### ISSUE THREAD

**Issue by SandroZaninello** [serverless/github-action#94]
Is there any possibility to specify the AWS region and Stage on "serverless deploy" command?
Simulating the command: "_sls deploy -r eu-west-1 -s dev_"
Something like:      
with:
        args: _deploy --r {{github.event.input.region}} --s {{github.event.input.stage}}_

**Comment by d3v3lop3rDE** [comment]
You should be able to use the args you provided

**Comment by SandroZaninello** [comment]
I'm encountering this error:

```
1 deprecation found: run 'serverless doctor' for more details
Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.MYPARAM": AWS profile "xyz" doesn't seem to be configured,
```
I also used aws-actions/configure-aws-credentials@v1 with role-to-assume.

In which way shoud I put the --aws-profile ?

**Comment by kaptain-karlo** [comment]
I can confirm that this:

```yaml
- name: Deploy Services
    uses: serverless/github-action@v4
    with:
      args: -c "cd ./apps/services && serverless deploy --stage=prod --region=eu-west-2"
      entrypoint: /bin/sh
```

Does not work. Im working in a monorepo and using the workaround in your readme. My github action failure logs show this:

`✖ Error: Cannot resolve '${env:DATABASE_URL}' variable at 'stages.default.params.databaseUrl'.`

I specifically set the stage to prod in my github action so yeah... It's busted
