### ISSUE TITLE
Cannot pass args to deploy command in monorepo

### ISSUE THREAD

**Issue by kaptain-karlo** [serverless/github-action#96]
I can confirm that this:

```yaml
- name: Deploy Services
    uses: serverless/github-action@v4
    with:
      args: -c "cd ./apps/services && serverless deploy --stage=prod --region=eu-west-2"
      entrypoint: /bin/sh
```
Does not work. Im working in a monorepo and using the workaround in your readme. My github action failure logs show this:

`✖ Error: Cannot resolve '${env:DATABASE_URL}' variable at 'stages.default.params.databaseUrl'.`

I specifically set the stage to prod in my github action so yeah... It's busted. My prod environment uses ${ssm} for the variables whilst my dev uses ${env}. 

Does anybody know how to get around this? Im using Serverless compose btw

**Comment by kaptain-karlo** [comment]
FIXED! 

Here's some pointers for anybody using serverless v4 w/ compose. If you have a default or dev stage, make sure to set the default value on all resolvers. Like this

```yaml
stages:
  default:
    params:
      databaseUrl: ${env:DATABASE_URL, ''}
   prod:
     params:
       databaseUrl: ${ssm:DATABASE_URL}
 ```
 
And make sure to add your SERVERLESS_ACCESS_KEY to the env.
