### ISSUE TITLE
Cannot find serverless/github-action@v4

### ISSUE THREAD

**Issue by mihirgupta0900** [serverless/github-action#98]
I was using the v4 of the action (as mentioned here: https://github.com/serverless/github-action/issues/91#issuecomment-2384074335) and was working find until yesterday.

Currently facing this error:
```
Error: Unable to resolve action `serverless/github-action@v4`, unable to find version `v4`
```

I do not see a v4 release and looks like this could be caused when this PR was merged: https://github.com/serverless/github-action/pull/97

This is currently blocking us and I think a new release needs to be published to fix this issue

**Comment by Andriy-Kulak** [comment]
I am getting the same issue :-(. I cannot deploy serverless using github actions.

@eahefnawy or @skierkowski - was anything changed in the last couple of days since I brought a related issue https://github.com/serverless/serverless/issues/12967 up?


![Screenshot 2025-01-03 at 4 03 27 p m](https://github.com/user-attachments/assets/47bd2f7d-f7cc-45db-8e78-9b02098082fc)

**Comment by skierkowski** [comment]
@czubocha can you have a look?

**Comment by mihirgupta0900** [comment]
Here's what I'm currently doing to deploy:
```yml
      - name: Install Serverless
        run: npm install -g serverless

      - name: NPM Install
        run: npm install

      - name: Serverless Deploy
        run: serverless deploy --debug --stage ${{ env.DGN }} --region ${{ env.AWS_REGION }} --force
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
```

**Comment by Andriy-Kulak** [comment]
thanks for the reference @mihirgupta0900. will try that on monday.

@czubocha @skierkowski, in case extra context is helpful, below is my simplified yaml github action config that is causing the "unable to resolve serverless/github-action@v4"  error

```yaml
name: ...
jobs:
  deploy:
    name: Deploy functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn install --frozen-lock-file

      - name: serverless deploy
        if: github.ref == 'refs/heads/main'
        uses: serverless/github-action@v4
        with:
          args: deploy --stage production
```
